export const hand = [
  {
    suite: 'spades',
    symbol: '♠',
    suiteColor: '\u001b[34m',
    cardUnicode: '🂮',
    kind: 'K',
    evaluatorCode: 'ks',
  },
  {
    suite: 'diamonds',
    symbol: '◆',
    suiteColor: '\u001b[31m',
    cardUnicode: '🃄',
    kind: '4',
    evaluatorCode: '4d',
  },
  {
    suite: 'diamonds',
    symbol: '◆',
    suiteColor: '\u001b[31m',
    cardUnicode: '🃁',
    kind: 'A',
    evaluatorCode: 'ad',
  },
  {
    suite: 'diamonds',
    symbol: '◆',
    suiteColor: '\u001b[31m',
    cardUnicode: '🃊',
    kind: '10',
    evaluatorCode: 'td',
  },
  {
    suite: 'clubs',
    symbol: '♣',
    suiteColor: '\u001b[34m',
    cardUnicode: '🃘',
    kind: '8',
    evaluatorCode: '8c',
  },
];
